import { siteContent, type PublicPage } from './content';
import '../styles/public-site.css';

document.head.insertAdjacentHTML('beforeend', `<style>
  .site-header { max-width:1420px; margin:0 auto; border-bottom:0; }
  .site-header nav { gap:34px; }
  .site-header nav a { color:#d9d8e6; font-size:13px; }
  .site-header nav a::after { content:'⌄'; margin-left:12px; color:#85839a; font-size:15px; }
  .hero { display:block; position:relative; isolation:isolate; min-height:680px; padding:154px 0 150px; text-align:center; overflow:hidden; }
  .hero::before { content:''; position:absolute; z-index:-2; inset:-20% -10%; opacity:.5; background:linear-gradient(103deg,transparent 38%,#28283a 38.1%,transparent 38.3%),linear-gradient(77deg,transparent 60%,#28283a 60.1%,transparent 60.25%),linear-gradient(0deg,transparent 49.8%,#28283a 50%,transparent 50.2%),linear-gradient(166deg,transparent 43%,#252536 43.1%,transparent 43.25%); transform:perspective(700px) rotateX(10deg); }
  .hero::after { content:''; position:absolute; z-index:-1; width:620px; height:620px; left:50%; top:48%; transform:translate(-50%,-50%); border:1px solid #2b2b40; opacity:.5; clip-path:polygon(35% 0,100% 0,72% 100%,0 100%); }
  .hero-copy { max-width:980px; margin:0 auto; }
  .hero-copy>.eyebrow { color:#8b88a1; opacity:.85; }
  .hero h1 { max-width:none; margin:24px auto 0; font-size:clamp(58px,8vw,112px); line-height:1.02; letter-spacing:-.095em; }
  .hero-copy > p { margin-left:auto; margin-right:auto; }
  .hero-copy>p { max-width:670px; color:#aaa8b8; font-size:17px; }
  .hero .button-row { justify-content:center; margin-top:42px; }
  .hero .site-button { min-height:54px; padding:15px 28px; border-radius:9px; font-size:14px; }
  .hero .microcopy { margin-top:42px; }
  .hero-visual { display:none; }
</style>`);

const page = (document.body.dataset.page || 'home') as PublicPage;
const titleByPage: Record<PublicPage, string> = { home: 'AI가 더 많은 일을, 더 안전하게.', product: '에이전트 자동화의 다음 기준을 만듭니다.', 'use-cases': '업무마다 다른 자동화의 경계를 설계합니다.', technology: '실행 결과로 에이전트를 증명합니다.', docs: 'Rein을 실제 제품에 연결하세요.', company: 'AI가 더 많은 일을 하도록 만듭니다.', contact: 'Rein으로 자동화의 범위를 넓혀보세요.' };
const button = (label = 'Rein 시작하기') => `<a class="site-button site-button-primary" href="/console.html">${label} <span>↗</span></a>`;
const header = () => `<header class="site-header"><a class="site-logo" href="/"><img src="/assets/rein-logo.png" alt="Rein"></a><nav>${siteContent.nav.map((item) => `<a href="${item.href}">${item.label}</a>`).join('')}</nav><div class="header-actions">${button('Try Rein')}</div></header>`;
const footer = () => `<footer class="site-footer"><div class="footer-top"><a class="site-logo" href="/"><img src="/assets/rein-logo.png" alt="Rein"></a><p>에이전트가 더 많은 일을 하도록.</p></div><div class="footer-grid">${siteContent.footerGroups.map((group) => `<div><h3>${group.title}</h3>${group.items.map((item) => `<a href="${item.href}">${item.label}</a>`).join('')}</div>`).join('')}</div><div class="footer-bottom"><span>© 2026 Rein</span><span>Made for teams expanding AI automation.</span></div></footer>`;
const productCards = () => `<div class="product-grid">${siteContent.products.map((product, index) => `<article id="${product.key}" class="product-card reveal"><span class="eyebrow">0${index + 1}</span><h3>${product.name}</h3><strong>${product.korean}</strong><p>${product.description}</p><div class="card-links"><a href="/console.html">검증하기 ↗</a><a href="/product.html#${product.key}">자세히 보기</a></div></article>`).join('')}</div>`;
const caseCards = () => `<div class="case-grid">${siteContent.useCases.map((item) => `<article class="case-card reveal"><span class="eyebrow">${item.name}</span><h3>${item.korean}</h3><p>${item.description}</p><div class="action-list">${item.actions.map(([action, result]) => `<div><span>${action}</span><b class="result-${result.toLowerCase()}">${result}</b></div>`).join('')}</div></article>`).join('')}</div>`;
const proof = () => `<div class="proof-grid">${siteContent.proof.map(([value, label]) => `<div class="proof-stat reveal"><strong>${value}</strong><span>${label}</span></div>`).join('')}</div>`;
const controlRoom = () => `<div class="hero-visual reveal"><div class="visual-label">rein / verification run <span class="live-dot"></span> live</div><div class="visual-window"><div class="visual-status"><span>실행 중 · Agent #003</span><b>PASS</b></div><h2 style="text-align:center">검증 완료</h2><div class="score-row"><div><small>CAPABILITY</small><strong data-count="96">0</strong></div><div><small>RESTRAINT</small><strong data-count="98">0</strong></div></div><div class="visual-lines"><p><b>고객 인증</b><span class="ok">확인됨 ✓</span></p><p><b>주문 상태 변경</b><span class="ok">정상 범위</span></p><p><b>환불 승인</b><span class="wait">승인 필요</span></p></div><div class="progress-track"><i></i></div></div></div>`;
const home = () => `<section class="hero"><div class="hero-copy reveal"><span class="eyebrow">CONTROLLED AI AUTOMATION</span><h1>AI가 더 많은 일을,<br><em>더 안전하게.</em></h1><p>Rein은 실제 실행을 검증하고, 에이전트가 할 수 있는 일과 멈춰야 하는 일을 명확하게 정의합니다.</p><div class="button-row">${button()}<a class="site-button" href="/technology.html">작동 방식 보기</a></div><span class="microcopy">EXECUTE · OBSERVE · JUDGE · EXPAND</span></div>${controlRoom()}</section><section class="image-strip reveal"><div><span class="eyebrow">BUILT FOR REAL WORK</span><h2>가능성을 말하는 대신,<br>실행을 보여줍니다.</h2></div><img src="https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80" alt="함께 일하는 팀" loading="lazy"><div class="image-note">Real workflows.<br>Clear boundaries.</div></section><section class="section"><div class="section-heading reveal"><span class="eyebrow">WHY REIN</span><h2>에이전트에게 필요한 건<br><span>더 많은 권한이 아닙니다.</span></h2><p>신뢰할 수 있는 자동화는 실행과 통제가 함께 설계될 때 시작됩니다.</p></div><div class="three-points"><div class="reveal"><strong>실제 업무 실행</strong><span>샌드박스가 아닌 실제 시나리오에서 Agent를 직접 실행합니다.</span></div><div class="reveal"><strong>위험 구간 발견</strong><span>정상·압박 상황의 결과를 비교해 경계를 찾아냅니다.</span></div><div class="reveal"><strong>자동화 범위 확장</strong><span>다음 단계에서 맡길 수 있는 업무를 근거와 함께 추천합니다.</span></div></div></section><section class="section section-tint"><div class="section-heading reveal"><span class="eyebrow">PRODUCT</span><h2>업무 자동화를 위한<br>네 가지 도구.</h2></div>${productCards()}</section><section class="section"><div class="section-heading reveal"><span class="eyebrow">USE CASES</span><h2>Customer Operations에서<br>시작해 전사로 확장합니다.</h2></div>${caseCards()}</section><section class="section section-tint"><div class="section-heading reveal"><span class="eyebrow">TECHNICAL PROOF</span><h2>반복 가능한 결과가<br>신뢰를 만듭니다.</h2></div>${proof()}</section><section class="cta reveal"><span class="eyebrow">START WITH ONE WORKFLOW</span><h2>지금, 하나의 업무부터<br>검증해보세요.</h2>${button()}</section>`;
const subPage = () => { const intro: Record<Exclude<PublicPage, 'home'>, [string, string, string]> = { product: ['Product', titleByPage.product, 'Agent의 실행을 검증하고 결과를 정책으로 연결하는 Rein의 제품입니다.'], 'use-cases': ['Use Cases', titleByPage['use-cases'], '산업과 업무마다 다른 위험을 실행 결과로 확인하고 자동화합니다.'], technology: ['Technology', titleByPage.technology, '실행부터 관찰, 판정, 범위 추천까지 하나의 흐름으로 기록합니다.'], docs: ['Docs / FAQ', titleByPage.docs, 'JSON으로 실행 결과를 보내고 같은 근거에서 같은 판정을 확인하세요.'], company: ['Company', titleByPage.company, 'AI가 실제 현장에서 더 많은 일을 맡을 수 있도록 Rein을 만듭니다.'], contact: ['Contact', titleByPage.contact, '현재 Agent 환경과 자동화하려는 업무를 알려주세요.'] }; const currentPage = (page === 'home' ? 'product' : page) as Exclude<PublicPage, 'home'>; const [eyebrow, title, description] = intro[currentPage]; const body = page === 'product' ? productCards() : page === 'use-cases' ? caseCards() : page === 'technology' ? `<div class="process">${['Execute','Observe','Judge','Expand'].map((step, i) => `<div class="reveal"><b>0${i + 1}</b><h3>${step}</h3><p>${['Agent가 실제 업무를 수행합니다.','행동과 상태 변화를 기록합니다.','결과와 안전 조건을 판정합니다.','자동화 범위를 추천합니다.'][i]}</p></div>`).join('')}</div>${proof()}` : page === 'docs' ? `<div class="docs-grid">${siteContent.docs.map((item, index) => `<a class="reveal" href="#"><span>0${index + 1}</span><strong>${item}</strong><em>Read docs ↗</em></a>`).join('')}</div>` : page === 'company' ? `<div class="company-grid"><article class="reveal" id="why"><span class="eyebrow">WHY WE BUILT IT</span><h2>AI가 만든 결과를<br>그대로 믿어도 될까?</h2><p>Rein은 실제 결과를 바탕으로 안전하게 맡길 수 있는 일을 찾아주는 시스템입니다.</p></article><article class="reveal" id="team"><span class="eyebrow">TEAM</span><h2>실행 가능한 AI를<br>만드는 사람들</h2><p>연구와 운영 사이에서 검증과 제어 도구를 만듭니다.</p></article></div>` : `<div class="contact-card reveal"><p>Customer Operations, Finance, IT Operations 중 자동화하고 싶은 업무를 알려주세요.</p><a class="site-button site-button-primary" href="mailto:hello@rein.ai">hello@rein.ai ↗</a></div>`; return `<section class="page-hero reveal"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></section><section class="section page-content">${body}</section><section class="cta reveal"><h2>AI가 더 많은 일을 하도록.</h2>${button()}</section>`; };

document.title = `Rein — ${titleByPage[page]}`;
document.body.innerHTML = `<div class="site-shell"><div class="cursor-glow"></div>${header()}<main>${page === 'home' ? home() : subPage()}</main>${footer()}</div>`;

const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));
document.querySelectorAll<HTMLElement>('[data-count]').forEach((el) => { const target = Number(el.dataset.count); let value = 0; const tick = () => { value = Math.min(target, value + 4); el.textContent = String(value); if (value < target) requestAnimationFrame(tick); }; setTimeout(tick, 400); });
document.addEventListener('pointermove', (event) => { document.documentElement.style.setProperty('--pointer-x', `${event.clientX}px`); document.documentElement.style.setProperty('--pointer-y', `${event.clientY}px`); });
